# we check this property at runtime to check if this file was included in the application.conf of the application using baker
baker.config-file-included = true
pekko.cluster.sharding.state-store-mode = persistence
pekko.actor.allow-java-serialization = off
