package com.ing.baker.openapi.dsl

import community.flock.wirespec.kotlin.Wirespec
import kotlin.reflect.KClass

/**
 * A single input ingredient an API operation expects (from path, query, headers, or
 * flattened request body fields). The runtime DSL turns each entry into a Baker
 * ingredient with the same name.
 */
data class InputField(
    val name: String,
    val type: KClass<*>,
)

/**
 * Descriptor for one OpenAPI operation. Implementations are generated by the plugin —
 * one `object` per operation — and are pure data plus a few callbacks the runtime
 * uses to build requests and invoke the wirespec handler.
 *
 * Each operation has at most one request body type; that type is the [RequestBody]
 * parameter on the descriptor. Operations without a body use [Unit].
 */
interface ApiOperation<RequestBody : Any> {
    /** Stable name for this operation. Used as the Baker interaction name. */
    val operationName: String

    /** Input ingredients in declaration order. */
    val inputFields: List<InputField>

    /** Maps HTTP status codes to the wirespec response class for that status. */
    val responseTypes: Map<Int, KClass<*>>

    /** The wirespec handler class this operation expects. The plugin generates this. */
    val handlerClass: KClass<out Wirespec.Handler>

    /**
     * Builds the wirespec Request from a name → value ingredient map. Used by the
     * default flat-ingredient flow when the recipe didn't declare an explicit
     * typed `inputFrom<E> { ... }` mapper.
     */
    fun buildRequest(ingredients: Map<String, Any?>): Any

    /**
     * Wraps a wirespec body DTO into the operation's Request envelope. Used by
     * the typed `inputFrom<E> { ... }` flow — the user lambda produces a value
     * of the operation's specific [RequestBody] type and the descriptor knows
     * how to put it into the Endpoint.Request.
     */
    fun buildRequestFromBody(body: RequestBody): Any

    /** Invokes the underlying wirespec handler. The handler must be of the operation's expected type. */
    suspend fun invoke(handler: Wirespec.Handler, request: Any): Wirespec.Response<*>

    /**
     * Builds the wirespec handler for this operation from a generic transport and
     * serialization. The default implementation lets the runtime construct handlers
     * for every API operation in a recipe from just (transport, serialization) —
     * the caller doesn't need to register handlers per operation.
     */
    fun buildHandler(
        transport: suspend (Wirespec.RawRequest) -> Wirespec.RawResponse,
        serialization: Wirespec.Serialization,
    ): Wirespec.Handler
}
