version: '3'
services:
  node1:
    image: "checkout-service-baker-example:3.0.1-SNAPSHOT"
    ports:
      - "8081:8080"
      - "5261:5266"
      - "9091:9095"
    #logging:
    #  driver: none
    environment:
      CLUSTER_HOST: node1
      CLUSTER_PORT: 2551
      CLUSTER_SEED_HOST: node1
      CLUSTER_SEED_PORT: 2551
  node2:
    image: "checkout-service-baker-example:3.0.1-SNAPSHOT"
    ports:
      - "8082:8080"
      - "5262:5266"
      - "9092:9095"
    #logging:
    #  driver: none
    environment:
      CLUSTER_HOST: node2
      CLUSTER_PORT: 2551
      CLUSTER_SEED_HOST: node1
      CLUSTER_SEED_PORT: 2551
  node3:
    image: "checkout-service-baker-example:3.0.1-SNAPSHOT"
    ports:
      - "8083:8080"
      - "5263:526"
      - "9093:9095"
    #logging:
    #  driver: none
    environment:
      CLUSTER_HOST: node3
      CLUSTER_PORT: 2551
      CLUSTER_SEED_HOST: node1
      CLUSTER_SEED_PORT: 2551
  prometheus:
    build: "./prometheus"
    container_name: "prometheus"
    ports:
      - "9090:9090"
  grafana:
    build: "./grafana"
    container_name: "grafana"
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    logging:
      driver: none
  haproxy:
    build: "./haproxy"
    container_name: "haproxy"
    ports:
      - "8080:8080"

  #elk:
    #image: sebp/elk
    #ports:
      # Kibana
      #- "5601:5601"
      # Elastic Search
      #- "9200:9200"
      # Logstash Beats interface
      #- "5044:5044"

