apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: interactions.ing-bank.github.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: ing-bank.github.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            image:
              type: string
            replicas:
              type: integer
              minimum: 1
            env:
              type: array
              items:
                oneOf:
                  - type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                    required: ["name", "value"]
                  - type: object
                    properties:
                      name:
                        type: string
                      valueFrom:
                        oneOf:
                          - type: object
                            properties:
                              configMapKeyRef:
                                type: object
                                properties:
                                  name:
                                    type: string
                                  key:
                                    type: string
                                required: ["name", "key"]
                            required: ["configMapKeyRef"]
                          - type: object
                            properties:
                              secretKeyRef:
                                type: object
                                properties:
                                  name:
                                    type: string
                                  key:
                                    type: string
                                required: ["name", "key"]
                            required: ["secretKeyRef"]
                    required: ["name", "valueFrom"]
            configMapMounts:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  mountPath:
                    type: string
                required: ["name", "mountPath"]
            secretMounts:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  mountPath:
                    type: string
                required: ["name", "mountPath"]
          required:
            - image
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: interactions
    # singular name to be used as an alias on the CLI and for display
    singular: interaction
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Interaction
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - int