apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: bakers.ing-bank.github.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: ing-bank.github.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            bakeryVersion:
              type: string
            replicas:
              type: integer
              minimum: 2
            recipes:
              type: array
              items:
                type: string
          required:
            - bakeryVersion
            - recipes
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: bakers
    # singular name to be used as an alias on the CLI and for display
    singular: baker
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Baker
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - ba
