{
 "title": "Kamon Akka",
 "description": "Kamon Akka Dashboard using Prometheus as Datasource",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(akka_actor_errors_total,instance)"
   },
   { "name": "path", "label": "Path", "query": "label_values(path)" },
   {
    "name": "class",
    "label": "Class",
    "query": "label_values(akka_actor_errors_total,class)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "percentile", "label": "Percentile", "query": "0.5,0.90,0.95,0.99,0.999" }
  ]
 },
 "panels": [
  {
   "title": "Avg Active Actors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(akka_system_active_actors_sum{instance=~\"$instance\"}[$interval]) / rate(akka_system_active_actors_count{instance=~\"$instance\"}[$interval])"
    }
   ]
  },
  { "title": "Akka System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Unhandled Messages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(akka_system_unhandled_messages_total{instance=~\"$instance\"}[$interval])) by (system)"
    }
   ]
  },
  {
   "title": "Dead Letters",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(akka_system_dead_letters_total{instance=~\"$instance\"}[$interval])) by (system)"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(akka_system_active_actors_count{instance=~\"$instance\"}[$interval])) by (system)",
     "legendFormat": "Active Actors"
    },
    {
     "expr": "sum(irate(akka_system_processed_messages_total{instance=~\"$instance\",tracked=\"true\"}[$interval])) by (system)",
     "legendFormat": "Processed Messages (tracked=true)"
    },
    {
     "expr": "sum(irate(akka_system_processed_messages_total{instance=~\"$instance\",tracked=\"false\"}[$interval])) by (system)",
     "legendFormat": "Processed Messages (tracked=false)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_actor_errors_total{instance=~\"$instance\",class=~\"$class\",path=~\"$path\"}[$interval])) by (path)",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum(irate(akka_group_errors_total{instance=~\"$instance\",class=~\"$class\"}[$interval])) by (group)",
     "legendFormat": "{{group}}"
    },
    {
     "expr": "sum(irate(akka_router_errors_total{instance=~\"$instance\",path=~\"$path\"}[$interval])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Akka Actor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Processing Time ($percentile)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(irate(akka_actor_processing_time_seconds_bucket{class=~\"$class\",path=~\"$path\",instance=~\"$instance\"}[$interval])) by (le, path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Time in Mailbox ($percentile)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(irate(akka_actor_time_in_mailbox_seconds_bucket{instance=~\"$instance\",class=~\"$class\",path=~\"$path\"}[$interval])) by (le, path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Mailbox Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_actor_mailbox_size_sum{instance=~\"$instance\",class=~\"$class\",path=~\"$path\"}[$interval])) by (path) / sum(irate(akka_actor_mailbox_size_count{instance=~\"$instance\",class=~\"$class\",path=~\"$path\"}[$interval])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Akka Group Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Processing Time ($percentile)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(irate(akka_group_processing_time_seconds_bucket{instance=~\"$instance\"}[$interval])) by (le, group)) * 1000",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Time in Mailbox ($percentile)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(irate(akka_group_time_in_mailbox_seconds_bucket{instance=~\"$instance\"}[$interval])) by (le, group))",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Mailbox Size / Number of Members",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(akka_group_mailbox_size_sum{instance=~\"$instance\"}[$interval]) / irate(akka_group_mailbox_size_count{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{group}} mailbox"
    },
    {
     "expr": "irate(akka_group_members_sum{instance=~\"$instance\"}[$interval]) / irate(akka_group_members_count{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{group}} members"
    }
   ]
  },
  { "title": "Akka Router Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Processing Time ($percentile)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(irate(akka_router_processing_time_seconds_bucket{path=~\"$path\",instance=~\"$instance\"}[$interval])) by (le, path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Time in Mailbox ($percentile)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(irate(akka_router_time_in_mailbox_seconds_bucket{instance=~\"$instance\",path=~\"$path\"}[$interval])) by (le, path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Routing Time ($percentile)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(irate(akka_router_routing_time_seconds_bucket{path=~\"$path\",instance=~\"$instance\"}[$interval])) by (le, path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Akka Remote Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Serialization Time ($percentile)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, irate(akka_remote_serialization_time_seconds_bucket{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{instance}} - {{direction}}"
    }
   ]
  },
  {
   "title": "Message Size",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_remote_message_size_bytes_sum{instance=~\"$instance\"}[$interval])) by (instance,direction) / sum(irate(akka_remote_message_size_bytes_count{instance=~\"$instance\"}[$interval])) by (instance,direction)",
     "legendFormat": "{{ instance }} - {{ direction }}"
    }
   ]
  },
  { "title": "Executor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Number Of Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(executor_threads_sum{instance=~\"$instance\"}[$interval]) / irate(executor_threads_count{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }}: {{ name }} ({{ state }})"
    }
   ]
  },
  {
   "title": "Number Of Tasks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(executor_tasks_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }}: {{ name }} ({{ state }})"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(executor_queue_sum{instance=~\"$instance\"}[$interval]) / irate(executor_queue_count{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }}: {{ name }} ({{ type }})"
    }
   ]
  }
 ]
}