name: CI
on:
  workflow_dispatch:
    inputs:
      submit_dependency_graph:
        description: 'Submit dependency graph (default: false)'
        required: false
        default: 'false'
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  ci:
    name: Build and test
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Run tests
        run: |
          if [ "${GITHUB_REF_NAME}" = "master" ]; then
            SUFFIX=""
          else
            SUFFIX="-${GITHUB_REF_NAME}"
          fi
          echo "REVISION=$(git describe | cut -c2-)$SUFFIX" >> $GITHUB_ENV
      - name: Run tests
        run: mvn clean install -Drevision=${{ env.REVISION }}
        env:
          AKKA_TOKEN: ${{ secrets.AKKA_TOKEN }}
      - name: Prepare draft release notes
        # Run this step only in the original repo and for pushes to the master branch or for tags starting with 'v'
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) && ! github.event.repository.fork }}
        continue-on-error: true
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-sonatype:
    permissions:
      contents: write
      pull-requests: write
    name: Publish to Sonatype
    # Publish to Sonatype only from the original repo and for the tags starting with 'v'
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && ! github.event.repository.fork }}
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Publish to Sonatype
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  publish-azure:
    permissions:
      contents: write
      pull-requests: write
    name: Publish to Azure
    # The job runs for:
    # - Any push to the repository.
    # - Pull requests from branches within the same repository (not forks).
    if: ${{ (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)) }}
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Publish to Azure
        run: mvn clean deploy -Drevision=${{ env.REVISION }} -DskipTests
        env:
          AZURE_FEEDUSER: ${{ secrets.AZURE_FEEDUSER }}
          AZURE_FEEDPASSWORD: ${{ secrets.AZURE_FEEDPASSWORD }}
          AZURE_FEEDURL: ${{ secrets.AZURE_FEEDURL }}
          AKKA_TOKEN: ${{ secrets.AKKA_TOKEN }}

  dependency-submission:
    name: Submit dependency graph
    continue-on-error: true
    needs: [ci]
    # Submit dependency graph only for the master branch commits or if workflow_dispatch input is set
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/master') || (github.event_name == 'workflow_dispatch' && inputs.submit_dependency_graph == 'true') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Generate dependency graph
        run: mvn dependency:tree -DoutputType=dot -DoutputFile=dependency-graph.dot
      - name: Submit dependency graph
        uses: github/dependency-submission-action@v4
        with:
          files: dependency-graph.dot
